arena:
  workstations:
    SH01: "SH"
    WS02: "10"
    WS03: "10"
    WS04: "00"
    PP01: "PP"
    TT01: "TT"
    WS07: "05"
    WS08: "05"
    WS09: "15"
    WS10: "05"
    WS11: "05"
    WS12: "00"
    WS13: "00"
    WS14: "10"
    WS15: "10"
    SH01: "SH"
    WS17: "15"
    WS18: "15"
  cavities: [ "F20_20_H", "F20_20_V", "S40_40_H", "S40_40_V", "M20_H", "M20_V", "M30_H", "M30_V", "M20_100_H", "R20_H", "R20_V" ]
  objects:
      F20_20_G      : 1
      F20_20_B      : 1
      S40_40_B      : 1
      S40_40_G      : 1
      M20           : 1
      M30           : 1
      M20_100       : 1
      R20           : 1
      Axis2         : 1
      Bearing2      : 1
      Housing       : 1
      Motor2        : 1
      Spacer        : 1
      Screwdriver   : 1
      Wrench        : 1
      Drill         : 1
      AllenKey      : 1
      CONTAINER_RED : 1
      CONTAINER_BLUE: 1
