arena:
  workstations:
    SH01: "SH"
    SH02: "SH"
    WS01: "10"
    WS02: "10"
    WS03: "00"
    WS04: "15"
    WS05: "15"
    WS06: "00"
    WS07: "00"
    WS08: "10"
    WS09: "10"
    WS10: "05"
    WS11: "05"
    WS12: "15"
    PP01: "PP"
    TT01: "TT"

  cavities: [ "F20_20_H", "F20_20_V", "S40_40_H", "S40_40_V", "M20_H", "M20_V", "M30_H", "M30_V", "M20_100_H", "R20_H", "R20_V" ]
  objects:
      F20_20_G      : 0 
      F20_20_B      : 0
      S40_40_B      : 0
      S40_40_G      : 10
      M20           : 10
      M30           : 10
      M20_100       : 10
      Axis2         : 10
      Bearing2      : 10
      Housing       : 10
      Motor2        : 10
      Spacer        : 10
      Screwdriver   : 10
      Wrench        : 10
      Drill         : 10
      AllenKey      : 10
      CONTAINER_RED : 1
      CONTAINER_BLUE: 1
